### ISSUE TITLE
Github Action for publishing project

### ISSUE THREAD

**Issue by denniscual** [denniscual/spinpack#1]
Create a Github Action to publish the project into NPM whenever there is new release.

Draft github action config:

```
name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: pnpm build

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

```

**Acceptance Criteria:**
- Create github action for publishing the project.
- Make sure to set up the npm token into secrets.
